services:
    hc-cache:
        image: redis:alpine3.20
        container_name: hc-cache
        ports:
            - '6379:6379'
        volumes:
            - ./hc-cache-data:/data
    hc-elasticsearch:
        container_name: hc-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
        environment:
            - xpack.security.enabled=false
            - 'discovery.type=single-node'
        ports:
            - 9200:9200
    hc-kibana:
        container_name: hc-kibana
        image: docker.elastic.co/kibana/kibana:7.11.0
        environment:
            - ELASTICSEARCH_HOSTS=http://hc-elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
volumes:
    hc-cache-data:
        driver: local
