services:
    hc-cache:
        image: redis:alpine3.20
        container_name: hc-cache
        ports:
            - '6379:6379'
        volumes:
            - ./hc-cache-data:/data
volumes:
    hc-cache-data:
        driver: local
